sintoma(febre).
sintoma(dor_cabeca).
sintoma(dor_muscular).
sintoma(dor_rosto).
sintoma(dor_peito).
sintoma(dor_garganta).
sintoma(dor_ouvido).
sintoma(dor_abdominal).
sintoma(dor_articular).
sintoma(fadiga).
sintoma(inchaco).
sintoma(rigidez).
sintoma(fraqueza).
sintoma(desconforto_peito).
sintoma(coceira).
sintoma(congestao_nasal).
sintoma(secrecao_nasal).
sintoma(dificuldade_engolir).
sintoma(nausea).
sintoma(vomito).
sintoma(calafrios).
sintoma(diarreia).
sintoma(ictericia).
sintoma(tosse).
sintoma(inflamacao_garganta).
sintoma(inflamacao_ganglios).
sintoma(falta_ar).
sintoma(confusao_mental).
sintoma(expectoracao).
sintoma(voz_rancha).
sintoma(palpitacao).
sintoma(ganho_peso).
sintoma(batimento_acelerado).
sintoma(tontura).
sintoma(desmaio).
sintoma(paralisia).
sintoma(dificuldade_na_fala).
sintoma(perda_visao).
sintoma(ansiedade).
sintoma(hemorragia_nasal).
sintoma(pulsacao_pescoco).
sintoma(manchas_na_pele).
sintoma(sangramento).
sintoma(vertigem).
sintoma(palidez).
sintoma(perda_equilibrio).
sintoma(zumbido_ouvido).
sintoma(inchaco_perna).