sintoma(febre_alta).
sintoma(dor_de_cabeca).
sintoma(dor_muscular).
sintoma(fadiga).
sintoma(nausea).
sintoma(vomito).
sintoma(ictericia).
sintoma(dor_rosto).
sintoma(congestao_nasal).
sintoma(secrecao_nasal).
sintoma(dor_garganta).
sintoma(tosse).
sintoma(falta_ar).
sintoma(dor_peito).
sintoma(confusao_mental).
sintoma(expectoracao).
sintoma(dor_garganta).
sintoma(dificuldade_engolir).
sintoma(dor_ouvido).
sintoma(inflamacao_garganta).
sintoma(ganglios_inflamados).
sintoma(voz_rancha).
sintoma(tosse_seca).
sintoma(febre_leve).
sintoma(inchaco_na_perna).
sintoma(palpitacao).
sintoma(ganho_peso).
sintoma(tosse_persistente).
sintoma(batimento_acelerado).
sintoma(tontura).
sintoma(desmaio).
sintoma(desconforto_no_peito).
sintoma(paralisia).
sintoma(dificuldade_na_fala).
sintoma(perda_visao).
sintoma(ansiedade).
sintoma(hemorragia_nasal).
sintoma(pulsacao_pescoco).
